services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      # Override service ports if needed
      - QDRANT__SERVICE__ENABLED_SERVICES=http,grpc
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      # Enable persistence
      - QDRANT__STORAGE__STORAGE_TYPE=rocksdb
    restart: unless-stopped